### ISSUE TITLE
Build initialization error: "ImportError: No module named pip._internal.cli.main"

### ISSUE THREAD

**Issue by emaxx-google** [GoogleChromeLabs/chromeos_smart_card_connector#115]
Running env/initialize.sh in a clean repository results in an error - presumably, due to the incorrect handling of the PIP downgrade in webports or gclient or PIP itself:

```
________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/webports.git /ssd/smartcard/chromeos_smart_card_connector.N
EW/env/webports/_gclient_src_xtu6rh5k' in 'chromeos_smart_card_connector/env/webports'
Cloning into 'chromeos_smart_card_connector/env/webports/_gclient_src_xtu6rh5k'...
remote: Counting objects: 1, done79 MiB ...Counting objects: 1           
remote: Total 28005 (delta 22006), reused 28005 (delta 22006)        
Receiving objects: 100% (28005/28005), 36.79 MiB | 34.69 MiB/s, done.
Resolving deltas: 100% (22006/22006), done.
Syncing projects: 100% (4/4), done.                        
Running hooks: 100% ( 2/ 2) pip_install
________ running 'src/build_tools/pip_install.sh' in 'chromeos_smart_card_connector/env/webports'
Installing pip..
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python
 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pip
  Downloading pip-20.1.1-py2.py3-none-any.whl (1.5 MB)
Collecting wheel
  Using cached wheel-0.34.2-py2.py3-none-any.whl (26 kB)
Installing collected packages: pip, wheel
Successfully installed pip-20.1.1 wheel-0.34.2
+ pip install --user pip==6.0.6
Traceback (most recent call last):
  File "chromeos_smart_card_connector/env/webports/src/out/pip/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ImportError: No module named pip._internal.cli.main
+ pip install --user --no-compile -r requirements.txt
Traceback (most recent call last):
  File "chromeos_smart_card_connector/env/webports/src/out/pip/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ImportError: No module named pip._internal.cli.main
```

**Comment by emaxx-google** [comment]
I don't fully understand where/why it regressed, but I discovered that patching the webports' src/build_tools/pip_install.sh to do "unset PYTHONNOUSERSITE" removes this error.

We can land this as a quick fix for now (perhaps the simplest way would be to import the whole "webports" repo under //third_party/, and then patch it there).
