### ISSUE TITLE
Flaky "Timed out receiving message from renderer" error in tests

### ISSUE THREAD

**Issue by emaxx-google** [GoogleChromeLabs/chromeos_smart_card_connector#1151]
```
make --directory=smart_card_connector_app/build/js_to_cxx_tests run_test
make[1]: Entering directory '/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/smart_card_connector_app/build/js_to_cxx_tests'
. ../../../env/python3_venv/bin/activate && \
	../../../common/js_test_runner/run-js-tests.py \
		out/integration_tests/index.html \
		--chrome-path=/usr/bin/google-chrome --chromedriver-path=../../../env/chromedriver --serve-via-web-server --timeout=3600 --chrome-arg="--enable-features=SharedArrayBuffer" 
Initializing environment...
Started web server 127.0.0.1:43741.
Running http://127.0.0.1:43741/index.html...
127.0.0.1 - - [15/Apr/2024 00:11:37] "GET /index.html HTTP/1.1" 200 -
127.0.0.1 - - [15/Apr/2024 00:11:37] "GET /tests.js HTTP/1.1" 200 -
127.0.0.1 - - [15/Apr/2024 00:11:37] "GET /integration_tests.js HTTP/1.1" 200 -
Waiting for the test completion...
127.0.0.1 - - [15/Apr/2024 00:11:37] code 404, message File not found
127.0.0.1 - - [15/Apr/2024 00:11:37] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [15/Apr/2024 00:11:37] "GET /integration_tests.data HTTP/1.1" 200 -
127.0.0.1 - - [15/Apr/2024 00:11:37] "GET /integration_tests.wasm HTTP/1.1" 200 -
127.0.0.1 - - [15/Apr/2024 00:11:37] "GET /integration_tests.worker.js HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/smart_card_connector_app/build/js_to_cxx_tests/../../../common/js_test_runner/run-js-tests.py", line 203, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/smart_card_connector_app/build/js_to_cxx_tests/../../../common/js_test_runner/run-js-tests.py", line 191, in main
    wait_for_test_completion(driver, args.timeout)
  File "/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/smart_card_connector_app/build/js_to_cxx_tests/../../../common/js_test_runner/run-js-tests.py", line 103, in wait_for_test_completion
    webdriver_ui.WebDriverWait(driver, timeout_seconds).until(
  File "/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/env/python3_venv/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 96, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/smart_card_connector_app/build/js_to_cxx_tests/../../../common/js_test_runner/run-js-tests.py", line 104, in <lambda>
    lambda driver: is_js_test_finished(driver) or is_page_load_failed(driver))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/smart_card_connector_app/build/js_to_cxx_tests/../../../common/js_test_runner/run-js-tests.py", line 134, in is_js_test_finished
    return driver.execute_script(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/env/python3_venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 407, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/env/python3_venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/env/python3_venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: chrome=123.0.6312.105)
```

**Comment by emaxx-google** [comment]
I saw these a couple of times recently - might be the Chrome 123 version that became slower or something...
