### ISSUE TITLE
CI fails on WebDriver "desired_capabilities" error

### ISSUE THREAD

**Issue by emaxx-google** [GoogleChromeLabs/chromeos_smart_card_connector#797]
Example run: https://github.com/GoogleChromeLabs/chromeos_smart_card_connector/actions/runs/5312458078/jobs/9616982582?pr=795 . Relevant logs:

```
Traceback (most recent call last):
  File "/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/common/js/build/unittests/../../../../common/js_test_runner/run-js-tests.py", line 135, in <module>
    sys.exit(main())
  File "/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/common/js/build/unittests/../../../../common/js_test_runner/run-js-tests.py", line 122, in main
    with create_driver(args.chromedriver_path) as driver:
  File "/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/common/js/build/unittests/../../../../common/js_test_runner/run-js-tests.py", line 52, in create_driver
    return webdriver.Chrome(service=service, options=options,
TypeError: __init__() got an unexpected keyword argument 'desired_capabilities'
```

**Comment by emaxx-google** [comment]
This seems to be backwards-incompatible change between Selenium 3.* and Selenium 4.*: https://www.selenium.dev/documentation/webdriver/getting_started/upgrade_to_selenium_4/#capabilities

(For the context, we use Selenium in order to run our unit tests that are written in JavaScript.)
