### ISSUE TITLE
CI test-asan fails with LeakSanitizer reports

### ISSUE THREAD

**Issue by emaxx-google** [GoogleChromeLabs/chromeos_smart_card_connector#799]
Example run: https://github.com/GoogleChromeLabs/chromeos_smart_card_connector/actions/runs/5313062131/jobs/9618434792?pr=798 . Relevant logs:

```
==41163==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 15904 byte(s) in 1 object(s) allocated from:
    #0 0x5689916b in __interceptor_realloc (/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/smart_card_connector_app/build/executable_module/cpp_unittests/out/cpp_unit_test_runner/cpp_unit_test_runner+0x2e816b) (BuildId: e488f7e34f45e78c0822e43dc0505a34a65235be)
    #1 0x56b536ae in HPReadBundleValues /home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/third_party/pcsc-lite/naclport/server/build/../../../../../third_party/pcsc-lite/src/src/hotplug_libusb.c:254:18
```

**Comment by emaxx-google** [comment]
This has been a recurring problem: see #792, #639 from previous hacks on this topic.

A proper solution would be to fix the PC/SC shutdown logic (so that it waits for the actual cleanup completion instead of just doing magic sleeps). However, we don't have spare development cycles at the moment, so we might need to bump the sleep in the asan+debug combination...
