### ISSUE TITLE
JS error when NaCl crashes and there's active client

### ISSUE THREAD

**Issue by emaxx-google** [GoogleChromeLabs/chromeos_smart_card_connector#823]
Just observed this on a test device after the Connector's NaCl module crashed (for an unrelated reason):

```
Uncaught TypeError: Cannot read properties of null (reading 'g')
    at I (background.js:101:481)
    at kl.A (background.js:456:49)
    at I (background.js:101:494)
    at background.js:457:296
    at H.A (background.js:101:911)
    at fl.A (background.js:451:41)
    at I (background.js:101:494)
    at background.js:450:325
    at H.A (background.js:101:911)
    at h.A (background.js:178:175)
```

The stack trace is obfuscated due to minification, but after comparing the minified and original code I think it's crashing in `ClientHandler.disposeInternal()`: https://github.com/GoogleChromeLabs/chromeos_smart_card_connector/blob/f4eb32264c2c2b7afe57db0cf8ee280c98ce9ae3/third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js#L211

**Comment by emaxx-google** [comment]
Suspecting this to be unintended side effect of the refactoring in #794. Viktoriia, could you PTAL? Thanks.
