### ISSUE TITLE
ASan test flakiness

### ISSUE THREAD

**Issue by emaxx-google** [GoogleChromeLabs/chromeos_smart_card_connector#951]
We observe flakiness in CI runs, especially on asan-debug bots. Example error:

```
=================================================================
==47338==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 15904 byte(s) in 1 object(s) allocated from:
    #0 0x56871beb in __interceptor_realloc (/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/smart_card_connector_app/build/executable_module/cpp_unittests/out/cpp_unit_test_runner/cpp_unit_test_runner+0x305beb) (BuildId: 6c3e6b3b3c3df359c5f049ce23192c4e560be175)
    #1 0x56b523af in HPReadBundleValues /home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/third_party/pcsc-lite/naclport/server/build/../../../../../third_party/pcsc-lite/src/src/hotplug_libusb.c:253:18
    #2 0x56b50f0f in HPSearchHotPluggables /home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/third_party/pcsc-lite/naclport/server/build/../../../../../third_party/pcsc-lite/src/src/hotplug_libusb.c:568:6
    #3 0x56b12c54 in google_smart_card::PcscLiteServerWebPortService::InitializeAndRunDaemonThread() /home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/third_party/pcsc-lite/naclport/server/build/../src/public/pcsc_lite_server_web_port_service.cc:259:17
    #4 0x568b1eaa in google_smart_card::Application::InitializeServicesOnBackgroundThread() /home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/smart_card_connector_app/build/executable_module/cpp_unittests/../../../src/application.cc:69:39
    #5 0x568b5e57 in void std::__invoke_impl<void, void (google_smart_card::Application::*)(), google_smart_card::Application*>(std::__invoke_memfun_deref, void (google_smart_card::Application::*&&)(), google_smart_card::Application*&&) /usr/bin/../lib/gcc-cross/i686-linux-gnu/12/../../../../i686-linux-gnu/include/c++/12/bits/invoke.h:74:14
    #6 0x568b5c49 in std::__invoke_result<void (google_smart_card::Application::*)(), google_smart_card::Application*>::type std::__invoke<void (google_smart_card::Application::*)(), google_smart_card::Application*>(void (google_smart_card::Application::*&&)(), google_smart_card::Application*&&) /usr/bin/../lib/gcc-cross/i686-linux-gnu/12/../../../../i686-linux-gnu/include/c++/12/bits/invoke.h:96:14
    #7 0x568b5bf1 in void std::thread::_Invoker<std::tuple<void (google_smart_card::Application::*)(), google_smart_card::Application*> >::_M_invoke<0u, 1u>(std::_Index_tuple<0u, 1u>) /usr/bin/../lib/gcc-cross/i686-linux-gnu/12/../../../../i686-linux-gnu/include/c++/12/bits/std_thread.h:279:13
    #8 0x568b5b80 in std::thread::_Invoker<std::tuple<void (google_smart_card::Application::*)(), google_smart_card::Application*> >::operator()() /usr/bin/../lib/gcc-cross/i686-linux-gnu/12/../../../../i686-linux-gnu/include/c++/12/bits/std_thread.h:286:11
    #9 0x568b57d1 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (google_smart_card::Application::*)(), google_smart_card::Application*> > >::_M_run() /usr/bin/../lib/gcc-cross/i686-linux-gnu/12/../../../../i686-linux-gnu/include/c++/12/bits/std_thread.h:231:13
    #10 0xf7dc0070  (/lib32/libstdc++.so.6+0xbf070) (BuildId: db9d23a4bd83319084b4dd57fffb36cacd2e8dfb)
    #11 0x5687d509 in __asan::AsanThread::ThreadStart(unsigned long long) (/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/smart_card_connector_app/build/executable_module/cpp_unittests/out/cpp_unit_test_runner/cpp_unit_test_runner+0x311509) (BuildId: 6c3e6b3b3c3df359c5f049ce23192c4e560be175)

Indirect leak of 47208 byte(s) in 562 object(s) allocated from:
    #0 0x5685b5ba in strdup (/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/smart_card_connector_app/build/executable_module/cpp_unittests/out/cpp_unit_test_runner/cpp_unit_test_runner+0x2ef5ba) (BuildId: 6c3e6b3b3c3df359c5f049ce23192c4e560be175)
    #1 0x56b521e7 in HPReadBundleValues /home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/third_party/pcsc-lite/naclport/server/build/../../../../../third_party/pcsc-lite/src/src/hotplug_libusb.c:233:44
    #2 0x56b50f0f in HPSearchHotPluggables /home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/third_party/pcsc-lite/naclport/server/build/../../../../../third_party/pcsc-lite/src/src/hotplug_libusb.c:568:6
    #3 0x56b12c54 in google_smart_card::PcscLiteServerWebPortService::InitializeAndRunDaemonThread() /home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/third_party/pcsc-lite/naclport/server/build/../src/public/pcsc_lite_server_web_port_service.cc:259:17
    #4 0x568b1eaa in google_smart_card::Application::InitializeServicesOnBackgroundThread() /home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/smart_card_connector_app/build/executable_module/cpp_unittests/../../../src/application.cc:69:39
    #5 0x568b5e57 in void std::__invoke_impl<void, void (google_smart_card::Application::*)(), google_smart_card::Application*>(std::__invoke_memfun_deref, void (google_smart_card::Application::*&&)(), google_smart_card::Application*&&) /usr/bin/../lib/gcc-cross/i686-linux-gnu/12/../../../../i686-linux-gnu/include/c++/12/bits/invoke.h:74:14
    #6 0x568b5c49 in std::__invoke_result<void (google_smart_card::Application::*)(), google_smart_card::Application*>::type std::__invoke<void (google_smart_card::Application::*)(), google_smart_card::Application*>(void (google_smart_card::Application::*&&)(), google_smart_card::Application*&&) /usr/bin/../lib/gcc-cross/i686-linux-gnu/12/../../../../i686-linux-gnu/include/c++/12/bits/invoke.h:96:14
    #7 0x568b5bf1 in void std::thread::_Invoker<std::tuple<void (google_smart_card::Application::*)(), google_smart_card::Application*> >::_M_invoke<0u, 1u>(std::_Index_tuple<0u, 1u>) /usr/bin/../lib/gcc-cross/i686-linux-gnu/12/../../../../i686-linux-gnu/include/c++/12/bits/std_thread.h:279:13
    #8 0x568b5b80 in std::thread::_Invoker<std::tuple<void (google_smart_card::Application::*)(), google_smart_card::Application*> >::operator()() /usr/bin/../lib/gcc-cross/i686-linux-gnu/12/../../../../i686-linux-gnu/include/c++/12/bits/std_thread.h:286:11
    #9 0x568b57d1 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (google_smart_card::Application::*)(), google_smart_card::Application*> > >::_M_run() /usr/bin/../lib/gcc-cross/i686-linux-gnu/12/../../../../i686-linux-gnu/include/c++/12/bits/std_thread.h:231:13
    #10 0xf7dc0070  (/lib32/libstdc++.so.6+0xbf070) (BuildId: db9d23a4bd83319084b4dd57fffb36cacd2e8dfb)
    #11 0x5687d509 in __asan::AsanThread::ThreadStart(unsigned long long) (/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/smart_card_connector_app/build/executable_module/cpp_unittests/out/cpp_unit_test_runner/cpp_unit_test_runner+0x311509) (BuildId: 6c3e6b3b3c3df359c5f049ce23192c4e560be175)

Indirect leak of 14633 byte(s) in 562 object(s) allocated from:
    #0 0x5685b5ba in strdup (/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/smart_card_connector_app/build/executable_module/cpp_unittests/out/cpp_unit_test_runner/cpp_unit_test_runner+0x2ef5ba) (BuildId: 6c3e6b3b3c3df359c5f049ce23192c4e560be175)
    #1 0x56b520b6 in HPReadBundleValues /home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/third_party/pcsc-lite/naclport/server/build/../../../../../third_party/pcsc-lite/src/src/hotplug_libusb.c:229:43
    #2 0x56b50f0f in HPSearchHotPluggables /home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/third_party/pcsc-lite/naclport/server/build/../../../../../third_party/pcsc-lite/src/src/hotplug_libusb.c:568:6
    #3 0x56b12c54 in google_smart_card::PcscLiteServerWebPortService::InitializeAndRunDaemonThread() /home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/third_party/pcsc-lite/naclport/server/build/../src/public/pcsc_lite_server_web_port_service.cc:259:17
    #4 0x568b1eaa in google_smart_card::Application::InitializeServicesOnBackgroundThread() /home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/smart_card_connector_app/build/executable_module/cpp_unittests/../../../src/application.cc:69:39
    #5 0x568b5e57 in void std::__invoke_impl<void, void (google_smart_card::Application::*)(), google_smart_card::Application*>(std::__invoke_memfun_deref, void (google_smart_card::Application::*&&)(), google_smart_card::Application*&&) /usr/bin/../lib/gcc-cross/i686-linux-gnu/12/../../../../i686-linux-gnu/include/c++/12/bits/invoke.h:74:14
    #6 0x568b5c49 in std::__invoke_result<void (google_smart_card::Application::*)(), google_smart_card::Application*>::type std::__invoke<void (google_smart_card::Application::*)(), google_smart_card::Application*>(void (google_smart_card::Application::*&&)(), google_smart_card::Application*&&) /usr/bin/../lib/gcc-cross/i686-linux-gnu/12/../../../../i686-linux-gnu/include/c++/12/bits/invoke.h:96:14
    #7 0x568b5bf1 in void std::thread::_Invoker<std::tuple<void (google_smart_card::Application::*)(), google_smart_card::Application*> >::_M_invoke<0u, 1u>(std::_Index_tuple<0u, 1u>) /usr/bin/../lib/gcc-cross/i686-linux-gnu/12/../../../../i686-linux-gnu/include/c++/12/bits/std_thread.h:279:13
    #8 0x568b5b80 in std::thread::_Invoker<std::tuple<void (google_smart_card::Application::*)(), google_smart_card::Application*> >::operator()() /usr/bin/../lib/gcc-cross/i686-linux-gnu/12/../../../../i686-linux-gnu/include/c++/12/bits/std_thread.h:286:11
    #9 0x568b57d1 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (google_smart_card::Application::*)(), google_smart_card::Application*> > >::_M_run() /usr/bin/../lib/gcc-cross/i686-linux-gnu/12/../../../../i686-linux-gnu/include/c++/12/bits/std_thread.h:231:13
    #10 0xf7dc0070  (/lib32/libstdc++.so.6+0xbf070) (BuildId: db9d23a4bd83319084b4dd57fffb36cacd2e8dfb)
    #11 0x5687d509 in __asan::AsanThread::ThreadStart(unsigned long long) (/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/smart_card_connector_app/build/executable_module/cpp_unittests/out/cpp_unit_test_runner/cpp_unit_test_runner+0x311509) (BuildId: 6c3e6b3b3c3df359c5f049ce23192c4e560be175)

Indirect leak of 8992 byte(s) in 562 object(s) allocated from:
    #0 0x5685b5ba in strdup (/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/smart_card_connector_app/build/executable_module/cpp_unittests/out/cpp_unit_test_runner/cpp_unit_test_runner+0x2ef5ba) (BuildId: 6c3e6b3b3c3df359c5f049ce23192c4e560be175)
    #1 0x56b522dc in HPReadBundleValues /home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/third_party/pcsc-lite/naclport/server/build/../../../../../third_party/pcsc-lite/src/src/hotplug_libusb.c:236:23
    #2 0x56b50f0f in HPSearchHotPluggables /home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/third_party/pcsc-lite/naclport/server/build/../../../../../third_party/pcsc-lite/src/src/hotplug_libusb.c:568:6
    #3 0x56b12c54 in google_smart_card::PcscLiteServerWebPortService::InitializeAndRunDaemonThread() /home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/third_party/pcsc-lite/naclport/server/build/../src/public/pcsc_lite_server_web_port_service.cc:259:17
    #4 0x568b1eaa in google_smart_card::Application::InitializeServicesOnBackgroundThread() /home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/smart_card_connector_app/build/executable_module/cpp_unittests/../../../src/application.cc:69:39
    #5 0x568b5e57 in void std::__invoke_impl<void, void (google_smart_card::Application::*)(), google_smart_card::Application*>(std::__invoke_memfun_deref, void (google_smart_card::Application::*&&)(), google_smart_card::Application*&&) /usr/bin/../lib/gcc-cross/i686-linux-gnu/12/../../../../i686-linux-gnu/include/c++/12/bits/invoke.h:74:14
    #6 0x568b5c49 in std::__invoke_result<void (google_smart_card::Application::*)(), google_smart_card::Application*>::type std::__invoke<void (google_smart_card::Application::*)(), google_smart_card::Application*>(void (google_smart_card::Application::*&&)(), google_smart_card::Application*&&) /usr/bin/../lib/gcc-cross/i686-linux-gnu/12/../../../../i686-linux-gnu/include/c++/12/bits/invoke.h:96:14
    #7 0x568b5bf1 in void std::thread::_Invoker<std::tuple<void (google_smart_card::Application::*)(), google_smart_card::Application*> >::_M_invoke<0u, 1u>(std::_Index_tuple<0u, 1u>) /usr/bin/../lib/gcc-cross/i686-linux-gnu/12/../../../../i686-linux-gnu/include/c++/12/bits/std_thread.h:279:13
    #8 0x568b5b80 in std::thread::_Invoker<std::tuple<void (google_smart_card::Application::*)(), google_smart_card::Application*> >::operator()() /usr/bin/../lib/gcc-cross/i686-linux-gnu/12/../../../../i686-linux-gnu/include/c++/12/bits/std_thread.h:286:11
    #9 0x568b57d1 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (google_smart_card::Application::*)(), google_smart_card::Application*> > >::_M_run() /usr/bin/../lib/gcc-cross/i686-linux-gnu/12/../../../../i686-linux-gnu/include/c++/12/bits/std_thread.h:231:13
    #10 0xf7dc0070  (/lib32/libstdc++.so.6+0xbf070) (BuildId: db9d23a4bd83319084b4dd57fffb36cacd2e8dfb)
    #11 0x5687d509 in __asan::AsanThread::ThreadStart(unsigned long long) (/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/smart_card_connector_app/build/executable_module/cpp_unittests/out/cpp_unit_test_runner/cpp_unit_test_runner+0x311509) (BuildId: 6c3e6b3b3c3df359c5f049ce23192c4e560be175)

Indirect leak of 8992 byte(s) in 562 object(s) allocated from:
    #0 0x5685b5ba in strdup (/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/smart_card_connector_app/build/executable_module/cpp_unittests/out/cpp_unit_test_runner/cpp_unit_test_runner+0x2ef5ba) (BuildId: 6c3e6b3b3c3df359c5f049ce23192c4e560be175)
    #1 0x56b52150 in HPReadBundleValues /home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/third_party/pcsc-lite/naclport/server/build/../../../../../third_party/pcsc-lite/src/src/hotplug_libusb.c:232:43
    #2 0x56b50f0f in HPSearchHotPluggables /home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/third_party/pcsc-lite/naclport/server/build/../../../../../third_party/pcsc-lite/src/src/hotplug_libusb.c:568:6
    #3 0x56b12c54 in google_smart_card::PcscLiteServerWebPortService::InitializeAndRunDaemonThread() /home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/third_party/pcsc-lite/naclport/server/build/../src/public/pcsc_lite_server_web_port_service.cc:259:17
    #4 0x568b1eaa in google_smart_card::Application::InitializeServicesOnBackgroundThread() /home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/smart_card_connector_app/build/executable_module/cpp_unittests/../../../src/application.cc:69:39
    #5 0x568b5e57 in void std::__invoke_impl<void, void (google_smart_card::Application::*)(), google_smart_card::Application*>(std::__invoke_memfun_deref, void (google_smart_card::Application::*&&)(), google_smart_card::Application*&&) /usr/bin/../lib/gcc-cross/i686-linux-gnu/12/../../../../i686-linux-gnu/include/c++/12/bits/invoke.h:74:14
    #6 0x568b5c49 in std::__invoke_result<void (google_smart_card::Application::*)(), google_smart_card::Application*>::type std::__invoke<void (google_smart_card::Application::*)(), google_smart_card::Application*>(void (google_smart_card::Application::*&&)(), google_smart_card::Application*&&) /usr/bin/../lib/gcc-cross/i686-linux-gnu/12/../../../../i686-linux-gnu/include/c++/12/bits/invoke.h:96:14
    #7 0x568b5bf1 in void std::thread::_Invoker<std::tuple<void (google_smart_card::Application::*)(), google_smart_card::Application*> >::_M_invoke<0u, 1u>(std::_Index_tuple<0u, 1u>) /usr/bin/../lib/gcc-cross/i686-linux-gnu/12/../../../../i686-linux-gnu/include/c++/12/bits/std_thread.h:279:13
    #8 0x568b5b80 in std::thread::_Invoker<std::tuple<void (google_smart_card::Application::*)(), google_smart_card::Application*> >::operator()() /usr/bin/../lib/gcc-cross/i686-linux-gnu/12/../../../../i686-linux-gnu/include/c++/12/bits/std_thread.h:286:11
    #9 0x568b57d1 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (google_smart_card::Application::*)(), google_smart_card::Application*> > >::_M_run() /usr/bin/../lib/gcc-cross/i686-linux-gnu/12/../../../../i686-linux-gnu/include/c++/12/bits/std_thread.h:231:13
    #10 0xf7dc0070  (/lib32/libstdc++.so.6+0xbf070) (BuildId: db9d23a4bd83319084b4dd57fffb36cacd2e8dfb)
    #11 0x5687d509 in __asan::AsanThread::ThreadStart(unsigned long long) (/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/smart_card_connector_app/build/executable_module/cpp_unittests/out/cpp_unit_test_runner/cpp_unit_test_runner+0x311509) (BuildId: 6c3e6b3b3c3df359c5f049ce23192c4e560be175)

SUMMARY: AddressSanitizer: 95729 byte(s) leaked in 2249 allocation(s).
make[1]: *** [../../../../common/cpp_unit_test_runner/src/build_analysis.mk:72: run_test] Error 1
make: *** [Makefile:162: test] Error 2
make[1]: Leaving directory '/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/smart_card_connector_app/build/executable_module/cpp_unittests'
```

**Comment by emaxx-google** [comment]
#949 landed that should reduce the flakiness rate and speed up tests significantly (because we get rid of hacky sleeps). But it seems that other problems exist, and also I'd need to upstream this change for maintainability.
